apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gctl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0032-tenant/tkrw-pr712-0075-0032-app/devfile-sample-gctl@sha256:35225cafbe8495f2e28a90c7ebaadf04bbf72f658fe9f9acba4958cfe9817842
        name: my-nodejs
        resources: {}
status: {}
